# Determine path separator depending on OS
my $sep = ($^O eq 'MSWin32') ? ';' : ':';


# Prepend parent directory to TEXINPUTS so LaTeX finds the style files
$ENV{'TEXINPUTS'} = "..//$sep" . ($ENV{'TEXINPUTS'} || "");

# Always create PDFs and set default engine to LuaLaTeX.
$pdf_mode = 4;

# Tell biber to also search the repo root for .bib files
$biber = 'biber --input-directory=.. %O %B';